# Домашнее задание 2 - предобработка признаков, pandas


### О задании

Практическое задание 2 посвящено изучению основных библиотек для анализа данных, а также линейных моделей и методов их обучения. Вы научитесь:
 * применять библиотеки NumPy и Pandas для осуществления желаемых преобразований;
 * подготавливать данные для обучения линейных моделей;
 * обучать линейную, Lasso и Ridge-регрессии при помощи модуля scikit-learn;
 * реализовывать обычный и стохастический градиентные спуски;
 * обучать линейную регрессию для произвольного функционала качества.
 

### Оценивание и штрафы

Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи). Максимально допустимая оценка за работу — 10 баллов. Кроме того, некоторые из заданий являются опциональными (необязательными), однако за их выполнение можно получить дополнительные баллы, которые позднее будут учитываться при проставлении оценок автоматом по курсу.

Сдавать задание после указанного срока сдачи нельзя. При выставлении неполного балла за задание в связи с наличием ошибок на усмотрение проверяющего предусмотрена возможность исправить работу на указанных в ответном письме условиях.

Задание выполняется самостоятельно. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов. Если вы нашли решение какого-то из заданий (или его часть) в открытом источнике, необходимо указать ссылку на этот источник в отдельном блоке в конце Вашей работы (скорее всего вы будете не единственным, кто это нашел, поэтому чтобы исключить подозрение в плагиате, необходима ссылка на источник). 

Неэффективная реализация кода может негативно отразиться на оценке.


### Формат сдачи
Для сдачи задания получившийся файл \*.ipynb с решением необходимо выложить в свой репозиторий github.

## Библиотеки для анализа данных

### NumPy

Во всех заданиях данного раздела запрещено использовать циклы  и list comprehensions. Под вектором и матрицей в данных заданиях понимается одномерный и двумерный numpy.array соответственно.

In [1]:
import numpy as np

**1. (0.2 балла)** Реализуйте функцию, возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответом является 5. Если нулевых элементов нет, функция должна возвращать None.


In [5]:
def max_element(arr):
    mask = arr == 0
    if not mask.any() or len(arr) <= 1:
        return None
    max_value = np.max(arr[1:][mask[:-1]])
    return max_value

In [6]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max_element(x)

5

**2. (0.2 балла)** Реализуйте функцию, принимающую на вход матрицу и некоторое число и возвращающую ближайший к числу элемент матрицы. Например: для X = np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4.

In [7]:
def nearest_value(X, v):
    diff = np.abs(X - v)
    min_index = np.unravel_index(diff.argmin(), diff.shape)
    nearest_element = X[min_index]
    return nearest_element

In [8]:
X = np.arange(0,10).reshape((2, 5))
v = 3.6
nearest_value(X, v)

4

**3. (0.2 балла)** Реализуйте функцию scale(X), которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает выборочное среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на случайной матрице (для её генерации можно использовать, например, функцию [numpy.random.randint](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html)).

In [10]:
def scale(X):
    means = np.mean(X, axis=0)
    stds = np.std(X, axis=0)
    stds[stds == 0] = 1
    scaled_X = (X - means) / stds
    return scaled_X

In [11]:
a = np.random.randint(0, 10, (5, 5))
print("Исходная матрица:")
print(a)

b = scale(a)
print("\nМасштабированная матрица:")
print(b)

Исходная матрица:
[[5 4 9 0 0]
 [4 6 0 7 5]
 [9 8 7 0 8]
 [4 7 0 2 6]
 [7 4 9 2 9]]

Масштабированная матрица:
[[-0.4125685  -1.125       0.96448564 -0.85895569 -1.7852148 ]
 [-0.92827912  0.125      -1.20560706  1.87408514 -0.19127301]
 [ 1.65027399  1.375       0.48224282 -0.85895569  0.76509206]
 [-0.92827912  0.75       -1.20560706 -0.07808688  0.12751534]
 [ 0.61885275 -1.125       0.96448564 -0.07808688  1.08388041]]


**4. (0.2 балла)** Реализуйте функцию, которая для заданной матрицы находит:
 - определитель
 - след
 - наименьший и наибольший элементы
 - норму Фробениуса
 - собственные числа
 - обратную матрицу

Для тестирования сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}$(10,1)

In [22]:
def get_stats(X):
    det = np.linalg.det(X)
    sled = np.trace(X)
    smallest = np.min(X)
    biggest = np.max(X)
    norm = np.linalg.norm(X, 'fro')  
    snumbers, _ = np.linalg.eig(a)
    inv = np.linalg.inv(X)
    print("Определитель: ", det, "\n\n", "След: ", sled, "\n\n", "Наименьший элемент: ",
          smallest, "\n\n", "Наибольший элемент: ", "\n\n", "Норма Фробениуса: ", norm, "\n\n",
          "Собственные числа: ", snumbers, "\n\n", "Обратная матрица: ", inv)

In [23]:
a = np.random.normal(10, 1, (3, 3))
print(a, "\n")
get_stats(a)

[[11.64199493 10.18651143 11.08073723]
 [11.07983993 11.57515906  9.2556966 ]
 [ 9.38836199 11.16060374 10.14995589]] 

Определитель:  70.82534161467827 

 След:  33.367109878817814 

 Наименьший элемент:  9.255696604654865 

 Наибольший элемент:  

 Норма Фробениуса:  31.940896977991308 

 Собственные числа:  [31.86074143+0.j          0.75318422+1.28673207j  0.75318422-1.28673207j] 

 Обратная матрица:  [[ 0.20032648  0.28626866 -0.47974406]
 [-0.36094505  0.19958623  0.21204306]
 [ 0.2115898  -0.48424808  0.3091129 ]]


**5. (0.2 балла)** Повторите 100 раз следующий эксперимент: сгенерируйте две матрицы размера 10×10 из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

In [83]:
max_elements = []

for exp_num in range(10000):
    a = np.random.randn(10, 10)
    b = np.random.randn(10, 10)
    c = np.dot(a, b)
    max_element = np.max(c)
    max_elements.append(max_element)

mean_max = np.mean(max_elements)
quantile_95 = np.percentile(max_elements, 95)
print("Среднее значение максимальных элементов:", mean_max)
print("95-процентная квантиль максимальных элементов:", quantile_95)

Среднее значение максимальных элементов: 8.416365148971105
95-процентная квантиль максимальных элементов: 11.886973452599452


Количество экспериментов я увеличил до 10000, это мне напомнило курс имитационного моделирования. Сделал я так для точности вычисления.

### Pandas

![](https://metrouk2.files.wordpress.com/2015/10/panda.jpg)

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные находятся в приложенном файле `2008.csv`. Их [описание](http://stat-computing.org/dataexpo/2009/the-data.html) приведено ниже:

Airline on-time performance

Have you ever been stuck in an airport because your flight was delayed or cancelled and wondered if you could have predicted it if you'd had more data? This is your chance to find out.

The data
The data set is available for download here.
The data consists of flight arrival and departure details for all commercial flights within the USA, from October 1987 to April 2008. This is a large dataset: there are nearly 120 million records in total, and takes up 1.6 gigabytes of space compressed and 12 gigabytes when uncompressed.

Understanding and preparing the data
In order to answer above questions, we are going to analyze the provided dataset, containing up to 1936758 ### different internal flights in the US for 2008 and their causes for delay, diversion and cancellation

The data comes from the U.S. Department of Transportation’s (DOT) Bureau of Transportation Statistics (BTS). Meta data explanations

This dataset is composed by the following variables:

**Year** 2008 **Month** 1-12 **DayofMonth** 1-31 **DayOfWeek** 1 (Monday) - 7 (Sunday)  
**DepTime** actual departure time (local, hhmm)  
**CRSDepTime** scheduled departure time (local, hhmm)  
**ArrTime** actual arrival time (local, hhmm)  
**CRSArrTime** scheduled arrival time (local, hhmm)  
**UniqueCarrier** unique carrier code  
**FlightNum** flight number  
**TailNum** plane tail number: aircraft registration, unique aircraft identifier  
**ActualElapsedTime** in minutes  
**CRSElapsedTime** in minutes  
**AirTime** in minutes  
**ArrDelay** arrival delay, in minutes: A flight is counted as “on time” if it operated less than 15 minutes later the scheduled time shown in the carriers’ Computerized Reservations Systems (CRS).  
**DepDelay** departure delay, in minutes  
**Origin** origin IATA airport code  
**Dest** destination IATA airport code  
**Distance** in miles  
**TaxiIn** taxi in time, in minutes  
**TaxiOut** taxi out time in minutes  
**Cancelled** *was the flight cancelled  
**CancellationCode** reason for cancellation (A = carrier, B = weather, C = NAS, D = security)  
**Diverted** 1 = yes, 0 = no  
**CarrierDelay** in minutes: Carrier delay is within the control of the air carrier. Examples of occurrences that may determine carrier delay are: aircraft cleaning, aircraft damage, awaiting the arrival of connecting passengers or crew, baggage, bird strike, cargo loading, catering, computer, outage-carrier equipment, crew legality (pilot or attendant rest), damage by hazardous goods, engineering inspection, fueling, handling disabled passengers, late crew, lavatory servicing, maintenance, oversales, potable water servicing, removal of unruly passenger, slow boarding or seating, stowing carry-on baggage, weight and balance delays.  
**WeatherDelay** in minutes: Weather delay is caused by extreme or hazardous weather conditions that are forecasted or manifest themselves on point of departure, enroute, or on point of arrival.  
**NASDelay** in minutes: Delay that is within the control of the National Airspace System (NAS) may include: non-extreme weather conditions, airport operations, heavy traffic volume, air traffic control, etc.  
**SecurityDelay** in minutes: Security delay is caused by evacuation of a terminal or concourse, re-boarding of aircraft because of security breach, inoperative screening equipment and/or long lines in excess of 29 minutes at screening areas.  
**LateAircraftDelay** in minutes: Arrival delay at an airport due to the late arrival of the same aircraft at a previous airport. The ripple effect of an earlier delay at downstream airports is referred to as delay propagation.

In [84]:
import pandas as pd
%matplotlib inline

In [85]:
data = pd.read_csv('2008.csv')
data

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0      2008      6          18          3   2111.0        2055   2308.0   
1      2008      6           4          3   1426.0        1410   1730.0   
2      2008      8           3          7   1143.0        1145   1501.0   
3      2008      1          23          3   1141.0        1144   1323.0   
4      2008      5           4          7    815.0         820   1243.0   
...     ...    ...         ...        ...      ...         ...      ...   
69995  2008      5          12          1   1829.0        1840   2137.0   
69996  2008      5          11          7   1149.0        1125   1336.0   
69997  2008      9          24          3   1012.0        1012   1132.0   
69998  2008      2          18          1   1906.0        1900   2200.0   
69999  2008     12           6          6    859.0         900    959.0   

       CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0            2300            WN        242  ...    3.0      8.0          0   
1            1728            XE       2380  ...    4.0     12.0          0   
2            1520            WN       1769  ...    4.0      9.0          0   
3            1335            OO       3802  ...    4.0     19.0          0   
4            1300            WN        399  ...    4.0      8.0          0   
...           ...           ...        ...  ...    ...      ...        ...   
69995        2149            DL        794  ...   22.0     20.0          0   
69996        1314            OO       6159  ...    4.0     13.0          0   
69997        1132            YV       7058  ...    7.0     10.0          0   
69998        2139            NW        641  ...   20.0     22.0          0   
69999        1005            WN        510  ...    2.0     12.0          0   

       CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0                   NaN         0           NaN          NaN      NaN   
1                   NaN         0           NaN          NaN      NaN   
2                   NaN         0           NaN          NaN      NaN   
3                   NaN         0           NaN          NaN      NaN   
4                   NaN         0           NaN          NaN      NaN   
...                 ...       ...           ...          ...      ...   
69995               NaN         0           NaN          NaN      NaN   
69996               NaN         0           0.0          0.0      0.0   
69997               NaN         0           NaN          NaN      NaN   
69998               NaN         0           0.0          0.0     15.0   
69999               NaN         0           NaN          NaN      NaN   

       SecurityDelay  LateAircraftDelay  
0                NaN                NaN  
1                NaN                NaN  
2                NaN                NaN  
3                NaN                NaN  
4                NaN                NaN  
...              ...                ...  
69995            NaN                NaN  
69996            0.0               22.0  
69997            NaN                NaN  
69998            0.0                6.0  
69999            NaN                NaN  

[70000 rows x 29 columns]

**6. (0.3 балла)** Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)

In [92]:
print(data.CancellationCode.value_counts().idxmax())
print(data.CancellationCode.value_counts().max())

A
563


**7. (0.3 балла)** Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.

In [93]:
data.Distance.mean()

724.5082571428571

In [94]:
data.Distance.max()

4962

In [95]:
data.Distance.min()

31

**8. (0.3 балла)** Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?

In [96]:
min_dist_data = data[data.Distance == data.Distance.min()]
min_dist_data[['Year', 'Month', 'DayofMonth', 'FlightNum']]

Year  Month  DayofMonth  FlightNum
1116   2008     12          30         65
6958   2008     12          26         65
17349  2008      8          18         64
27534  2008      3          11         64
46082  2008      8           9         65
48112  2008      2          28         64

In [100]:
distance = data[(data.FlightNum == 64) | (data.FlightNum == 65)][['FlightNum','Distance']].reset_index()
distance.sort_values(by = ['Distance','FlightNum'], ascending = False)

index  FlightNum  Distance
20  14646         65      2454
37  32956         65      2454
76  68338         65      2454
4    2619         64      2381
11   7891         64      2381
..    ...        ...       ...
10   6958         65        31
48  46082         65        31
22  17349         64        31
30  27534         64        31
52  48112         64        31

[78 rows x 3 columns]

**9. (0.3 балла)** Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?

In [103]:
airport = data.Origin.value_counts()
most_departures_airport = airport.idxmax()
print(most_departures_airport)

ATL


ATL видимо Атланта.

**10. (0.3 балла)** Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?

In [104]:
average_airtime_by_airport = data.groupby('Origin')['AirTime'].mean()
airport_with_max_average_airtime = average_airtime_by_airport.idxmax()
print("Аэропорт с наибольшим средним временем полета:", airport_with_max_average_airtime)

Аэропорт с наибольшим средним временем полета: SJU


**11. (0.5 балла)** Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [107]:
total_flights_by_airport = data.groupby('Origin')['Year'].count()
filtered_airports = total_flights_by_airport[total_flights_by_airport >= 1000]
filtered_data = data[data.Origin.isin(filtered_airports.index)]
delayed_flights_by_airport = filtered_data[filtered_data.DepDelay > 0].groupby('Origin')['Year'].count()
airport_with_highest_delay_percentage = (delayed_flights_by_airport / total_flights_by_airport).idxmax()
airport_with_highest_delay_percentage

'EWR'

## Линейная регрессия

В этой части мы разберемся с линейной регрессией, способами её обучения и измерением качества ее прогнозов. 

Будем рассматривать датасет из предыдущей части задания для предсказания времени задержки отправления рейса в минутах (DepDelay). Отметим, что под задержкой подразумевается не только опоздание рейса относительно планируемого времени вылета, но и отправление до планируемого времени.

### Подготовка данных

**12. (0.5 балла)** Считайте выборку из файла при помощи функции pd.read_csv и ответьте на следующие вопросы:
   - Имеются ли в данных пропущенные значения?
   - Сколько всего пропущенных элементов в таблице "объект-признак"?
   - Сколько объектов имеют хотя бы один пропуск?
   - Сколько признаков имеют хотя бы одно пропущенное значение?

In [108]:
data = pd.read_csv("2008.csv")
data

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0      2008      6          18          3   2111.0        2055   2308.0   
1      2008      6           4          3   1426.0        1410   1730.0   
2      2008      8           3          7   1143.0        1145   1501.0   
3      2008      1          23          3   1141.0        1144   1323.0   
4      2008      5           4          7    815.0         820   1243.0   
...     ...    ...         ...        ...      ...         ...      ...   
69995  2008      5          12          1   1829.0        1840   2137.0   
69996  2008      5          11          7   1149.0        1125   1336.0   
69997  2008      9          24          3   1012.0        1012   1132.0   
69998  2008      2          18          1   1906.0        1900   2200.0   
69999  2008     12           6          6    859.0         900    959.0   

       CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0            2300            WN        242  ...    3.0      8.0          0   
1            1728            XE       2380  ...    4.0     12.0          0   
2            1520            WN       1769  ...    4.0      9.0          0   
3            1335            OO       3802  ...    4.0     19.0          0   
4            1300            WN        399  ...    4.0      8.0          0   
...           ...           ...        ...  ...    ...      ...        ...   
69995        2149            DL        794  ...   22.0     20.0          0   
69996        1314            OO       6159  ...    4.0     13.0          0   
69997        1132            YV       7058  ...    7.0     10.0          0   
69998        2139            NW        641  ...   20.0     22.0          0   
69999        1005            WN        510  ...    2.0     12.0          0   

       CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0                   NaN         0           NaN          NaN      NaN   
1                   NaN         0           NaN          NaN      NaN   
2                   NaN         0           NaN          NaN      NaN   
3                   NaN         0           NaN          NaN      NaN   
4                   NaN         0           NaN          NaN      NaN   
...                 ...       ...           ...          ...      ...   
69995               NaN         0           NaN          NaN      NaN   
69996               NaN         0           0.0          0.0      0.0   
69997               NaN         0           NaN          NaN      NaN   
69998               NaN         0           0.0          0.0     15.0   
69999               NaN         0           NaN          NaN      NaN   

       SecurityDelay  LateAircraftDelay  
0                NaN                NaN  
1                NaN                NaN  
2                NaN                NaN  
3                NaN                NaN  
4                NaN                NaN  
...              ...                ...  
69995            NaN                NaN  
69996            0.0               22.0  
69997            NaN                NaN  
69998            0.0                6.0  
69999            NaN                NaN  

[70000 rows x 29 columns]

In [113]:
missing_values = data.isnull()
have_missing_values = missing_values.any().any()
total_missing = missing_values.sum().sum()
objects_with_missing = missing_values.any(axis=1).sum()
features_with_missing = missing_values.any().sum()

print(have_missing_values)
print(total_missing)
print(objects_with_missing)
print(features_with_missing)

True
306866
63404
13


Как вы понимаете, также не имеет смысла рассматривать при решении поставленной задачи объекты с пропущенным значением целевой переменной. В связи с этим ответьте на следующие вопросы и выполните соответствующие действия:
- Имеются ли пропущенные значения в целевой переменной?
- Проанализируйте объекты с пропущенными значениями целевой переменной. Чем вызвано это явление? Что их объединяет? Можно ли в связи с этим, на ваш взгляд, исключить какие-то признаки из рассмотрения? Обоснуйте свою точку зрения.

Исключите из выборки объекты **с пропущенным значением целевой переменной и со значением целевой переменной, равным 0**, а также при необходимости исключите признаки в соответствии с вашим ответом на последний вопрос из списка и выделите целевую переменную в отдельный вектор, исключив её из матрицы "объект-признак".

In [111]:
missing_dep_delay = data['DepDelay'].isnull().any()
print("Имеются ли пропущенные значения в целевой переменной (DepDelay)?", missing_dep_delay)

Имеются ли пропущенные значения в целевой переменной (DepDelay)? True


In [112]:
data = data.dropna(subset=['DepDelay'])
data = data[data['DepDelay'] != 0]

X = data.drop(columns=['DepDelay'])
y = data['DepDelay']

data

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0      2008      6          18          3   2111.0        2055   2308.0   
1      2008      6           4          3   1426.0        1410   1730.0   
2      2008      8           3          7   1143.0        1145   1501.0   
3      2008      1          23          3   1141.0        1144   1323.0   
4      2008      5           4          7    815.0         820   1243.0   
...     ...    ...         ...        ...      ...         ...      ...   
69994  2008      1          26          6    920.0         925   1110.0   
69995  2008      5          12          1   1829.0        1840   2137.0   
69996  2008      5          11          7   1149.0        1125   1336.0   
69998  2008      2          18          1   1906.0        1900   2200.0   
69999  2008     12           6          6    859.0         900    959.0   

       CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0            2300            WN        242  ...    3.0      8.0          0   
1            1728            XE       2380  ...    4.0     12.0          0   
2            1520            WN       1769  ...    4.0      9.0          0   
3            1335            OO       3802  ...    4.0     19.0          0   
4            1300            WN        399  ...    4.0      8.0          0   
...           ...           ...        ...  ...    ...      ...        ...   
69994        1118            OH       5218  ...   12.0     13.0          0   
69995        2149            DL        794  ...   22.0     20.0          0   
69996        1314            OO       6159  ...    4.0     13.0          0   
69998        2139            NW        641  ...   20.0     22.0          0   
69999        1005            WN        510  ...    2.0     12.0          0   

       CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0                   NaN         0           NaN          NaN      NaN   
1                   NaN         0           NaN          NaN      NaN   
2                   NaN         0           NaN          NaN      NaN   
3                   NaN         0           NaN          NaN      NaN   
4                   NaN         0           NaN          NaN      NaN   
...                 ...       ...           ...          ...      ...   
69994               NaN         0           NaN          NaN      NaN   
69995               NaN         0           NaN          NaN      NaN   
69996               NaN         0           0.0          0.0      0.0   
69998               NaN         0           0.0          0.0     15.0   
69999               NaN         0           NaN          NaN      NaN   

       SecurityDelay  LateAircraftDelay  
0                NaN                NaN  
1                NaN                NaN  
2                NaN                NaN  
3                NaN                NaN  
4                NaN                NaN  
...              ...                ...  
69994            NaN                NaN  
69995            NaN                NaN  
69996            0.0               22.0  
69998            0.0                6.0  
69999            NaN                NaN  

[63404 rows x 29 columns]

**13. (0.5 балла)** Обратите внимание, что признаки DepTime, CRSDepTime, ArrTime, CRSArrTime приведены в формате hhmm, в связи с чем будет не вполне корректно рассматривать их как вещественные.

Преобразуйте каждый признак FeatureName из указанных в пару новых признаков FeatureName\_Hour, FeatureName\_Minute, разделив каждое из значений на часы и минуты. Не забудьте при этом исключить исходный признак из выборки. В случае, если значение признака отсутствует, значения двух новых признаков, его заменяющих, также должны отсутствовать. 

Например, признак DepTime необходимо заменить на пару признаков DepTime_Hour, DepTime_Minute. При этом, например, значение 155 исходного признака будет преобразовано в значения 1 и 55 признаков DepTime_Hour, DepTime_Minute соответственно.

In [114]:
def convert_to_hour_and_minute(value):
    if pd.notna(value):
        hour = int(value // 100)
        minute = int(value % 100)
        return hour, minute
    else:
        return None, None

data['DepTime_Hour'], data['DepTime_Minute'] = zip(*data['DepTime'].map(convert_to_hour_and_minute))
data = data.drop(columns=['DepTime'])
data['CRSDepTime_Hour'], data['CRSDepTime_Minute'] = zip(*data['CRSDepTime'].map(convert_to_hour_and_minute))
data = data.drop(columns=['CRSDepTime'])
data['ArrTime_Hour'], data['ArrTime_Minute'] = zip(*data['ArrTime'].map(convert_to_hour_and_minute))
data = data.drop(columns=['ArrTime'])
data['CRSArrTime_Hour'], data['CRSArrTime_Minute'] = zip(*data['CRSArrTime'].map(convert_to_hour_and_minute))
data = data.drop(columns=['CRSArrTime'])
data1 = data.copy()

data1

Year  Month  DayofMonth  DayOfWeek UniqueCarrier  FlightNum TailNum  \
0      2008      6          18          3            WN        242  N699SW   
1      2008      6           4          3            XE       2380  N15980   
2      2008      8           3          7            WN       1769  N464WN   
3      2008      1          23          3            OO       3802  N465SW   
4      2008      5           4          7            WN        399  N489WN   
...     ...    ...         ...        ...           ...        ...     ...   
69994  2008      1          26          6            OH       5218  N655CA   
69995  2008      5          12          1            DL        794  N988DL   
69996  2008      5          11          7            OO       6159  N776SK   
69998  2008      2          18          1            NW        641  N318US   
69999  2008     12           6          6            WN        510  N786SW   

       ActualElapsedTime  CRSElapsedTime  AirTime  ...  SecurityDelay  \
0                   57.0            65.0     46.0  ...            NaN   
1                  124.0           138.0    108.0  ...            NaN   
2                  138.0           155.0    125.0  ...            NaN   
3                  102.0           111.0     79.0  ...            NaN   
4                  148.0           160.0    136.0  ...            NaN   
...                  ...             ...      ...  ...            ...   
69994              110.0           113.0     85.0  ...            NaN   
69995              128.0           129.0     86.0  ...            NaN   
69996               47.0            49.0     30.0  ...            0.0   
69998              234.0           219.0    192.0  ...            0.0   
69999               60.0            65.0     46.0  ...            NaN   

       LateAircraftDelay DepTime_Hour DepTime_Minute  CRSDepTime_Hour  \
0                    NaN           21             11               20   
1                    NaN           14             26               14   
2                    NaN           11             43               11   
3                    NaN           11             41               11   
4                    NaN            8             15                8   
...                  ...          ...            ...              ...   
69994                NaN            9             20                9   
69995                NaN           18             29               18   
69996               22.0           11             49               11   
69998                6.0           19              6               19   
69999                NaN            8             59                9   

       CRSDepTime_Minute  ArrTime_Hour  ArrTime_Minute CRSArrTime_Hour  \
0                     55          23.0             8.0              23   
1                     10          17.0            30.0              17   
2                     45          15.0             1.0              15   
3                     44          13.0            23.0              13   
4                     20          12.0            43.0              13   
...                  ...           ...             ...             ...   
69994                 25          11.0            10.0              11   
69995                 40          21.0            37.0              21   
69996                 25          13.0            36.0              13   
69998                  0          22.0             0.0              21   
69999                  0           9.0            59.0              10   

       CRSArrTime_Minute  
0                      0  
1                     28  
2                     20  
3                     35  
4                      0  
...                  ...  
69994                 18  
69995                 49  
69996                 14  
69998                 39  
69999                  5  

[63404 rows x 33 columns]

**14. (0.5 балла)** Некоторые из признаков, отличных от целевой переменной, могут оказывать чересчур значимое влияние на прогноз, поскольку по своему смыслу содержат большую долю информации о значении целевой переменной. Изучите описание датасета и исключите признаки, сильно коррелирующие с ответами. Ваш выбор признаков для исключения из выборки обоснуйте. Кроме того, исключите признаки TailNum и Year.

In [22]:
import seaborn as sns
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'seaborn'

In [23]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)



[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: C:\Users\tidaa\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


**15. (1 балл)** Приведем данные к виду, пригодному для обучения линейных моделей. Для этого вещественные признаки надо отмасштабировать, а категориальные — привести к числовому виду. Также надо устранить пропуски в данных.

В первую очередь поймем, зачем необходимо применять масштабирование. Следующие ячейки с кодом построят гистограммы для 3 вещественных признаков выборки.

In [ ]:
X['DepTime_Hour'].hist(bins=20)

In [ ]:
X['TaxiIn'].hist(bins=20)

In [ ]:
X['FlightNum'].hist(bins=20)

Какую проблему вы наблюдаете на этих графиках? Как масштабирование поможет её исправить?

Некоторые из признаков в нашем датасете являются категориальными. Типичным подходом к работе с ними является бинарное, или [one-hot-кодирование](https://en.wikipedia.org/wiki/One-hot).

Реализуйте функцию transform_data, которая принимает на вход DataFrame с признаками и выполняет следующие шаги:
1. Замена пропущенных значений на нули для вещественных признаков и на строки 'nan' для категориальных.
2. Масштабирование вещественных признаков с помощью [StandardScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).
3. One-hot-кодирование категориальных признаков с помощью [DictVectorizer](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.DictVectorizer.html) или функции [pd.get_dummies](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html).

Метод должен возвращать преобразованный DataFrame, который должна состоять из масштабированных вещественных признаков и закодированных категориальных (исходные признаки должны быть исключены из выборки).

In [ ]:
def transform_data(data):
    # Your code here

Примените функцию transform_data к данным. Сколько признаков получилось после преобразования?

In [ ]:
# Your code here

**16. (0.5 балла)** Разбейте выборку и вектор целевой переменной на обучение и контроль в отношении 70/30 (для этого можно использовать, например, функцию [train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.train_test_split.html)). 

In [ ]:
# Your code here

### Scikit-learn

<img src = "https://pp.vk.me/c4534/u35727827/93547647/x_d31c4463.jpg">
Теперь, когда мы привели данные к пригодному виду, попробуем решить задачу при помощи метода наименьших квадратов. Напомним, что данный метод заключается в оптимизации функционала $MSE$:

$$MSE(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 \to \min_{w},$$

где $\{ (x_i, y_i ) \}_{i=1}^l$ — обучающая выборка, состоящая из $l$ пар объект-ответ.

Заметим, что решение данной задачи уже реализовано в модуле sklearn в виде класса [LinearRegression](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression).

**17. (0.5 балла)** Обучите линейную регрессию на 1000 объектах из обучающей выборки и выведите значения $MSE$ и $R^2$ на этой подвыборке и контрольной выборке (итого 4 различных числа). Проинтерпретируйте полученный результат — насколько качественные прогнозы строит полученная модель? Какие проблемы наблюдаются в модели?

**Подсказка**: изучите значения полученных коэффициентов $w$, сохраненных в атрибуте coef_ объекта LinearRegression.

In [ ]:
# Your code here

Для решения описанных вами в предыдущем пункте проблем используем L1- или L2-регуляризацию, тем самым получив Lasso и Ridge регрессии соответственно и изменив оптимизационную задачу одним из следующих образов:
$$MSE_{L1}(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 + \alpha ||w||_1 \to \min_{w},$$
$$MSE_{L2}(X, y) = \frac{1}{l} \sum_{i=1}^l (<w, x_i> - y_i)^2 + \alpha ||w||_2^2 \to \min_{w},$$

где $\alpha$ — коэффициент регуляризации. Один из способов его подбора заключается в переборе некоторого количества значений и оценке качества на кросс-валидации для каждого из них, после чего выбирается значение, для которого было получено наилучшее качество.

In [ ]:
# Your code here

__18. (1 балл) __ Обучение линейной регрессии.



Обучите линейную регрессию с $L_1$ (Lasso) и $L_2$ (Ridge) регуляризаторами (используйте параметры по умолчанию). Посмотрите, какое количество коэффициентов близко к 0 (степень близости к 0 определите сами из разумных пределов). Постройте график зависимости числа ненулевых коэффициентов от коэффицента регуляризации (перебирайте значения по логарифмической сетке от $10^{-3}$ до $10^3$). Согласуются ли результаты с вашими ожиданиями?

In [ ]:
# Your code here
# ...

Посчитайте для Ridge-регрессии следующие метрики: $RMSE$, $MAE$, $R^2$.

In [ ]:
# Your code here
# ...

Подберите на обучающей выборке для Ridge-регрессии коэффициент регуляризации (перебирайте значения по логарифмической сетке от $10^{-3}$ до $10^3$) для каждой из метрик при помощи кросс-валидации c 5 фолдами на тех же 1000 объектах. Для этого воспользуйтесь GridSearchCV и KFold из sklearn. Постройте графики зависимости фукнции потерь от коэффициента регуляризации. Посчитайте те же метрики снова. Заметно ли изменилось качество?

Для выполнения данного задания вам могут понадобиться реализованные в библиотеке объекты [LassoCV](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html), [RidgeCV](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeCV.html) и [KFold](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.KFold.html).

In [ ]:
# Your code here
# ...

__19. (0.5 балла)__ Поиск объектов-выбросов


Как известно, MSE сильно штрафует за большие ошибки на объектах-выбросах. С помощью cross_val_predict сделайте Out-of-Fold предсказания для обучающей выборки. Посчитайте ошибки и посмотрите на их распределение (plt.hist). Что вы видите?